config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users

  resources :products do
    get :who_bought, on: :member
  end

  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    root 'store#index', as: 'store', via: :all
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Pragprog Books Online Store</title>
		<%= csrf_meta_tags %>

		<%= stylesheet_link_tag 'application', media: 'all',
'data-turbolinks-track': 'reload' %>

		<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
	</head>

	<body>
		<header class="main">
			<%= form_tag store_path, class: 'locale' do %> 
				<%= select_tag 'set_locale',
					options_for_select(LANGUAGES, I18n.locale.to_s),
					onchange: 'this.form.submit()' %>
				<%= submit_tag 'submit' %>
				<%= javascript_tag "$('.locale input').hide()" %>
			<% end %>
			<%= image_tag 'logo.svg', alt: 'The Pragmatic Bookshelf' %>
			<h1><%= @page_title || t('.title') %></h1>
		</header>
		<section class="content">
			<nav class="side_nav">

				<div id="cart" class="carts">

					<%= render_if @cart && @cart.line_items.any?, @cart %>
				</div>

				<ul>
					<li><a href="http://www...."><%= t('.home') %></a></li>
					<li><a href="http://www..../faq"><%= t('.questions') %></a></li>
					<li><a href="http://www..../news"><%= t('.news') %></a></li>
					<li><a href="http://www..../contact"><%= t('.contact') %></a></li>
				</ul>

				<% if session[:user_id] %>
					<ul>
						<li><%= link_to 'Orders', orders_path %></li>
						<li><%= link_to 'Products', products_path %></li>
						<li><%= link_to 'Users', users_path %></li>
					</ul>
					<%= button_to 'Logout', logout_path, method: :delete %>
				<% end %>
			</nav>
			
			<main class='<%= controller.controller_name %>'>
				<%= yield %>
			</main>
		</section>
	</body>
</html>